# The RegisterSubControllerManager service allows a distributed controller
# manager to register itself at the central controller manager

# Req:
# To register a controller the distributed sub controller manager has to 
# define:
#   * the full namespace it operates in 
#   * all statePublishers the sub controller provides

# Res:
# The response includes:
#   * a bool if the registration succeeded 

string sub_controller_manager_namespace
string sub_controller_manager_name
controller_manager_msgs/StatePublisherDescription[] state_publishers
---
bool ok